### PR TITLE
Added BF16 to word2vec benchmark

### PR DESCRIPTION
**Pull request by arlesniak**
Added BF16 to word2vec benchmark

### CODE REVIEW

**Review by lidanqing-intel — DISMISSED** [review]
LGTM.

**Comment by arlesniak** [comment]
@jczaja @wozna @arogowie-intel Could you please start you review?

**Review by arogowie-intel — DISMISSED** [review]

**Review by arogowie-intel — APPROVED** [review]

**Review by lidanqing-intel — APPROVED** [review]
LGTM

**Review by frankwhzhang — APPROVED** [review]
LGTM

**Pull request merged**
