### PR TITLE
Fix for missing dependency in word2vec BF16 benchmark

### PR DESCRIPTION
**Pull request by arlesniak**
Fix for missing dependency in word2vec BF16 benchmark

### CODE REVIEW

**Review by jczaja — APPROVED** [review]
LGTM

**Comment by lidanqing-intel** [comment]
@lidanqing-intel

**Review by lidanqing-intel — APPROVED** [review]
LGTM.

**Comment by lidanqing-intel** [comment]
@wzzju Could you please help merge this PR? Thanks !

**Review by frankwhzhang — APPROVED** [review]
LGTM

**Pull request merged**
